### PR TITLE
Clarify SCG4 usage documentation

### PR DESCRIPTION
**Pull request by nicolerg**
Add documentation to resolve Issue #104 and preclude independent Conda installation

### CODE REVIEW

**Comment by leepc12** [comment]
Thanks for your effort to improve our pipeline documentation.

`source activate encode-atac-seq-pipeline` already exists in the shell script for `sbatch`. `module load miniconda/3` should be added to that `.sh` right below [`module load java`](https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/examples/sherlock/ENCSR356KRQ_subsampled_sherlock_conda.sh#L36).

**Comment by nicolerg** [comment]
I would highly recommend at least replacing the step that explains how to install `conda` in the SCG documentation with `module load miniconda/3` before installing dependencies. There is no need for SCG users to install `conda`, and doing so changes the `$PATH` to point to the fresh install of python that lacks modules required for other tools, thereby causing errors for other processes. Any SCG users unaware of `module load miniconda/3` would run into the same problem.

**Comment by leepc12** [comment]
Sure, but I am still not sure if that shared conda on SCG will work fine with our pipeline. Let's fix issue #107 first and then I will update the documentation.

**Comment by nicolerg** [comment]
`module load minconda/3` has consistently been working well.

**Comment by leepc12** [comment]
@nicolerg: Thanks, will merge this in the next release.

**Comment by nicolerg** [comment]
I just updated the README and added `module load miniconda/3` to the two SCG examples as you suggested.

**Comment by leepc12** [comment]
Closing this because it's included in PR #114.

**Pull request closed without merging**
